services:
  - type: web
    name: korea-music-chart-api
    env: java
    rootDir: korea-music-chart-api
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw -DskipTests clean package
    startCommand: java -jar target/music-chart-api-0.1.jar
    autoDeploy: true
