services:
  - type: web
    name: korea-music-chart-api
    runtime: docker
    plan: free
    dockerfilePath: korea-music-chart-api/Dockerfile
    dockerContext: korea-music-chart-api
    autoDeployTrigger: commit
